import HelpLayout from "./about/layout";
import NavBar from "../components/NavBar";
import { ThemeProvider } from "../contexts/ThemeContext";
import ThemeToggleButton from "../components/ThemeToggleButton";

export const metadata = {
  title: {
    default:"Next.js",
    template: '%s | Next.js',
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko"> 
      <body>
      <ThemeProvider>
        <header>
          <h1>===== Header =====</h1>
          <NavBar></NavBar>
          <ThemeToggleButton/>
        </header>
        <main>{children}</main>
        <footer>
          ----- Footer -----
        </footer>
        </ThemeProvider>
      </body>
      
    </html>
  );
}
