import HelpLayout from "./about/layout";
import NavBar from "../components/NavBar";

export const metadata = {
  title: {
    default:"Next.js",
    template: '%s | Next.js',
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <body>
        <header>
          <h1>===== Header =====</h1>
          <NavBar></NavBar>
        </header>
        <main>{children}</main>
        <footer>
          ----- Footer -----
        </footer>
      </body>
    </html>
  );
}
