
import NavBar from "./components/NavBar";

export const metadata = {
  title: {
    default:"Next.js",
    template: '%s | Next.js',
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko"> 
      <body>  
        <header>          
          <NavBar></NavBar>
        </header>
        <main>{children}</main>
        <footer>  
        </footer> 
      </body>  
    </html>
  );
}
